
# Transponse

In [1]:
import numpy

In [4]:

a = numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n' , a)
b = numpy.transpose(a)
print('b\n' ,b)
print(a.T)

a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 50]
 [20 60]
 [30 70]
 [40 80]]
[[10 50]
 [20 60]
 [30 70]
 [40 80]]


# Inverse

In [5]:
a = numpy.matrix(((10,20),(30,40)))
b = numpy.linalg.inv(a)
#          linear algebra inverse
print('a\n' ,a)
print('inverse a\n' ,b)


a
 [[10 20]
 [30 40]]
inverse a
 [[-0.2   0.1 ]
 [ 0.15 -0.05]]


# identity matrix

In [6]:
c=a*b
print('identity matrix\n' , c)


identity matrix
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# get x , y

In [7]:
a= numpy.matrix(((2,5),(3,10)))
b= numpy.matrix(((20,),(35,)))
c= numpy.linalg.inv(a)
print('a\n',a)
print('b\n',b)
print('inv of a\n',c)
d=c*b
print('d\n', d)

a
 [[ 2  5]
 [ 3 10]]
b
 [[20]
 [35]]
inv of a
 [[ 2.  -1. ]
 [-0.6  0.4]]
d
 [[5.]
 [2.]]


# identity matrix

In [8]:
a = numpy.identity(10)
print('identity matrix\n',a)


identity matrix
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# save numpy matrix

In [ ]:
import numpy
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120)))
numpy.save('amat',a)

In [ ]:
#load the file
a=numpy.load('amat.npy')
print(a)

# store in txt file

In [ ]:
a = numpy.matrix(((10,20),(30,40)))
numpy.savetxt('saveTxt',a)

In [ ]:
#load txt file
a=numpy.loadtxt('saveTxt')
print(a)