# Convert comprass matrix it's orignal Matrix

In [1]:
import numpy
import scipy.sparse
a = numpy.matrix(((0,0,0,1),(1,0,1,0),(0,0,0,0),(0,0,0,1),(0,1,0,0)))
print(type(a))
print('a\n',a)
sc = scipy.sparse.csr_matrix(a)
print('a in compressed from \n',sc)
print(type(sc))
b = sc.toarray()
print('b\n',b)
print(type(b))

# it provide a ndarrya \n now we convert into matrix

c = numpy.matrix(b)
print('c\n',c)
print(type(c))


<class 'numpy.matrix'>
a
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
a in compressed from 
   (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (3, 3)	1
  (4, 1)	1
<class 'scipy.sparse._csr.csr_matrix'>
b
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.ndarray'>
c
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.matrix'>


# Ek row me karte hai matrix ko 
###
 `(Flatten karte hai)`

In [2]:
import numpy
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*50)
b=a.flatten('C')
print('b\n',b)



a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
--------------------------------------------------
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]


---
isme flatten by defalut row ko marge kar ke ooutput deta hai<br>
isme 4 options hote hai but ml me 2 importent hote hai
1. row waise jisme flatten('c') hota but flatten() by default c hi hota hai
2. column waise jisme flatten('F') hota hai

In [3]:
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
print("Row flatten")
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*59)

print("column flatten")
b=a.flatten('F')
print('b\n',b)






Row flatten
a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
-----------------------------------------------------------
column flatten
b
 [[ 10  50  90 130  20  60 100 140  30  70 110 150  40  80 120 160]]


In [4]:
a=numpy.matrix(((1,2,3,4,41),(5,6,7,8,81),(9,10,11,12,91)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
c=b.reshape(5,3)
print('c\n',c)

d=b.reshape(3,5)
print('d\n',d)


a
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]
b
 [[ 1  2  3  4 41  5  6  7  8 81  9 10 11 12 91]]
c
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]
d
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]


In [5]:
#you can reshape matrix directly

e=a.reshape(5,3)
print('e\n',e)

e
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]


In [6]:
# can not be left any element
f=a.reshape(2,4) # Wrong
# and not add any element using reshape
f=a.reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (2,4)

# Importent Point releated to reference

In [ ]:
import numpy
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



In [ ]:
# if you need to make a copy

a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.copy()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



In [ ]:
# another operation is view()
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.view()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)


print(id(a),id(b))

print("diff is A obj , B obj  -> is point to main obj ")

print("prof of concept :")
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
b=a
c=a.copy()
d=a.view()

print('id of a\n',id(a))
print('id of b\n',id(b))
print('id of c\n',id(c))
print('id of d\n',id(d))

print('a,b address is same \nbut c,d address are not same')


In [ ]:
# crate a element with a range
a=numpy.arange(100)
print('a\n',a)
b=a.reshape(5,20)
print('b\n',b)
#-------------------
print("-"*40)
c=numpy.arange(50).reshape(2,25)
print('c\n',c)


In [ ]:
a=numpy.random.randint(100,size=50)
print('a\n',a)
print(type(a))
b = numpy.random.randint(100,size=(5,4))
print('b\n',b)
print(type(b))

c=numpy.matrix(b)
print('c\n',c)
print(type(c))


In [ ]:
a = numpy.random.choice([10,2,3,-1,540,40,30],size=(5,8))
print('a\n',a)

In [ ]:
# When pass a functions
def get_max(a):
    max = a[0]
    for x in range(1, len(a)):
        if a[x] > max:
            max = a[x]
    return max


a = numpy.random.randint(100, size=(5, 4))
print("a\n", a)
print(type(a))

# find max element in every row
c = numpy.apply_along_axis(get_max, 1, a)
print("c\n", c)
print(type(c))

# find max element in every columns
c = numpy.apply_along_axis(get_max, 0, a)
print("c\n", c)
