# Convert comprass matrix it's orignal Matrix

In [2]:
import numpy
import scipy.sparse
a = numpy.matrix(((0,0,0,1),(1,0,1,0),(0,0,0,0),(0,0,0,1),(0,1,0,0)))
print(type(a))
print('a\n',a)
sc = scipy.sparse.csr_matrix(a)
print('a in compressed from \n',sc)
print(type(sc))
b = sc.toarray()
print('b\n',b)
print(type(b))

# it provide a ndarrya \n now we convert into matrix

c = numpy.matrix(b)
print('c\n',c)
print(type(c))


<class 'numpy.matrix'>
a
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
a in compressed from 
   (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (3, 3)	1
  (4, 1)	1
<class 'scipy.sparse._csr.csr_matrix'>
b
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.ndarray'>
c
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.matrix'>


# Ek row me karte hai matrix ko 
###
 `(Flatten karte hai)`

In [3]:
import numpy
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*50)
b=a.flatten('C')
print('b\n',b)



a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
--------------------------------------------------
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]


---
isme flatten by defalut row ko merge kar ke output deta hai<br>
isme 4 options hote hai but ml me 2 importent hote hai
1. row waise jisme flatten('c') hota but flatten() by default c hi hota hai
2. column waise jisme flatten('F') hota hai

In [4]:
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
print("Row flatten")
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*59)

print("column flatten")
b=a.flatten('F')
print('b\n',b)






Row flatten
a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
-----------------------------------------------------------
column flatten
b
 [[ 10  50  90 130  20  60 100 140  30  70 110 150  40  80 120 160]]


In [5]:
a=numpy.matrix(((1,2,3,4,41),(5,6,7,8,81),(9,10,11,12,91)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
c=b.reshape(5,3)
print('c\n',c)

d=b.reshape(3,5)
print('d\n',d)


a
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]
b
 [[ 1  2  3  4 41  5  6  7  8 81  9 10 11 12 91]]
c
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]
d
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]


In [6]:
#you can reshape matrix directly

e=a.reshape(5,3)
print('e\n',e)

e
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]


In [7]:
# can not be left any element
f=a.reshape(2,4) # Wrong
# and not add any element using reshape
f=a.reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (2,4)

# Importent Point releated to reference

In [8]:
import numpy
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[1010   20   30   40]
 [  50   60   70   80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]


In [9]:
# if you need to make a copy

a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.copy()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]


In [10]:
# another operation is view()
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.view()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)


print(id(a),id(b))

print("diff is A obj , B obj  -> is point to main obj ")

print("prof of concept :")
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
b=a
c=a.copy()
d=a.view()

print('id of a\n',id(a))
print('id of b\n',id(b))
print('id of c\n',id(c))
print('id of d\n',id(d))

print('a,b address is same \nbut c,d address are not same')


a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[1010   20   30   40]
 [  50   60   70   80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]
140185727740496 140185727740160
diff is A obj , B obj  -> is point to main obj 
prof of concept :
id of a
 140185727740272
id of b
 140185727740272
id of c
 140185727740160
id of d
 140185727722768
a,b address is same 
but c,d address are not same


In [11]:
# crate a element with a range
a=numpy.arange(100)
print('a\n',a)
b=a.reshape(5,20)
print('b\n',b)
#-------------------
print("-"*40)
c=numpy.arange(50).reshape(2,25)
print('c\n',c)


a
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
b
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
----------------------------------------
c
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [13]:
a=numpy.random.randint(100,size=50)
print('a\n',a)
print(type(a))
b = numpy.random.randint(100,size=(5,4))
print('b\n',b)
print(type(b))

c=numpy.matrix(b)
print('c\n',c)
print(type(c))


a
 [35 24 53 12 67  6 19 89 16 81 73  4 91 56 82 60 73 52 44 78 73 94 95 47
 36 13 75 54 18 64  5 96 22 87  5 84 37  3 35 63  8 14 33 71 26 73 72  1
 14 57]
<class 'numpy.ndarray'>
b
 [[46  0 36  4]
 [ 4 93 82 94]
 [96  6  2 98]
 [83 21 62 19]
 [45 31 16 31]]
<class 'numpy.ndarray'>
c
 [[46  0 36  4]
 [ 4 93 82 94]
 [96  6  2 98]
 [83 21 62 19]
 [45 31 16 31]]
<class 'numpy.matrix'>


In [15]:
a = numpy.random.choice([10,2,3,-1,540,40,30],size=(5,8))
print('a\n',a)

a
 [[ -1   2  40 540  30  -1  10 540]
 [ 10  10   3  30   3  -1 540   3]
 [ 30  30  40   3   2   2  40 540]
 [ 40   3  30 540  30  10 540  30]
 [ 10  -1  30  30  40  40   3  40]]


In [32]:
# When pass a functions
def get_max(a):
    max = a[0]
    for x in range(1, len(a)):
        if a[x] > max:
            max = a[x]
    return max

a = numpy.random.randint(100, size=(5, 4))
print("a\n", a)
print(type(a))
# a = numpy.matrix(a)
# find max element in every row
c = numpy.apply_along_axis(get_max, 1, a)
print("c\n", c)
print(type(c))

# find max element in every columns
c = numpy.apply_along_axis(get_max, 0, a)
print("c\n", c)


a
 [[60 82 74 53]
 [40 74 65 83]
 [19 74 20 56]
 [35 72 35 62]
 [ 5  5 54 76]]
<class 'numpy.ndarray'>
c
 [82 83 74 72 76]
<class 'numpy.ndarray'>
c
 [60 82 74 83]


In [33]:
# apply_along_axis works with ndarray

def t_mx(a):
    return max(a)

c = numpy.apply_along_axis(t_mx, 0, a)
print("c\n", c)

c = numpy.apply_along_axis(lambda x : max(x), 0, a)
print("c\n", c)

c = numpy.apply_along_axis(lambda x : max(x), 1, a)
print("c\n", c)

c
 [60 82 74 83]
c
 [60 82 74 83]
c
 [82 83 74 72 76]
