# Feature Scaling 
# all the distance based algorithem have a one issue , it reflact the performatce
### studied_hour , IQ , problem solved , package , state (happy/unhappy)
> - now we need focuse on package , whenever we find the distance .the algo is baies of package ,becouse of this we loss the importance of other features (f1,f2,f3)
> - for find the right value we need to scale the table (all values are in same level) , that's called <mark> Feature Scaling <mark>

for scale the data we use veriouse processes like 
- **Mean Normalization**
- **Standarization**
- **MIN-MAX-SCALING**
- Robust scaling
- Max abs scaling
- power transfer
- unit vector
- and more .......


In [1]:
import numpy 
study_hour =[3, 4, 5, 4, 5, 6, 2]
IQ = [100, 20, 40, 140, 40, 10, 20]
gfg_quetion_solved = [10,20,15,5,15,15,15]
package = [500000, 400000, 750000, 850000, 700000, 650000, 450000]

table = numpy.matrix((study_hour,IQ,gfg_quetion_solved,package)).T
print(table)

[[     3    100     10 500000]
 [     4     20     20 400000]
 [     5     40     15 750000]
 [     4    140      5 850000]
 [     5     40     15 700000]
 [     6     10     15 650000]
 [     2     20     15 450000]]


In [2]:
# Mean Normalization
# x-mean(set(x))/max(set(x))-min(set(x))

mean_arr = numpy.mean(table , axis=0)
max_arr = numpy.max(table,axis=0)
min_arr = numpy.min(table,axis=0)
print(mean_arr)
print(max_arr)
print(min_arr)

def get_mean_normalization(a):
    return [(a[x]-mean_arr[x])/(max_arr[x]-min_arr[x]) for x in range(len(a))]
# mat=numpy.apply_along_axis(lambda a:[(a[x]-mean_arr[x])/(max_arr[x]-min_arr[x]) for x in range(len(a))],1,table)
mat = numpy.apply_along_axis(get_mean_normalization,1,table)
scaled_table=numpy.matrix(mat)
print('*'*50)
print('scaled table now all the cloumn are equal level')
print(scaled_table)

[[4.14285714e+00 5.28571429e+01 1.35714286e+01 6.14285714e+05]]
[[     6    140     20 850000]]
[[     2     10      5 400000]]
**************************************************
scaled table now all the cloumn are equal level
[[-0.28571429  0.36263736 -0.23809524 -0.25396825]
 [-0.03571429 -0.25274725  0.42857143 -0.47619048]
 [ 0.21428571 -0.0989011   0.0952381   0.3015873 ]
 [-0.03571429  0.67032967 -0.57142857  0.52380952]
 [ 0.21428571 -0.0989011   0.0952381   0.19047619]
 [ 0.46428571 -0.32967033  0.0952381   0.07936508]
 [-0.53571429 -0.25274725  0.0952381  -0.36507937]]


In [3]:
# Standarization
import statistics
# x-mean(set(x))/            (math.sqrt((x-mean(set(x)))**2/n)) # std deviation
mean_arr = numpy.mean(table , axis=0)
print(mean_arr)

# mean_=numpy.mean(table , axis=0)
# sub = numpy.subtract(table,mean_)
# square_=numpy.square(sub)
# variance = numpy.mean(square_,axis=0)
# std_arr = numpy.sqrt(variance)
std_arr=numpy.std(table,axis=0)
print(std_arr)


def get_standarization(a):
        return [(a[i]-mean_arr[i])/std_arr[i] for i in range(len(a))]

mat = numpy.apply_along_axis(get_standarization,1,table)
scaled_table=numpy.matrix(mat)
print('*'*50)
print('scaled table now all the cloumn are equal level')
print(scaled_table)

[[4.14285714e+00 5.28571429e+01 1.35714286e+01 6.14285714e+05]]
[[1.24539970e+00 4.49489506e+01 4.40315286e+00 1.55182578e+05]]
**************************************************
scaled table now all the cloumn are equal level
[[-0.91766294  1.04880885 -0.81110711 -0.73645969]
 [-0.11470787 -0.73098799  1.45999279 -1.38086193]
 [ 0.6882472  -0.28603878  0.32444284  0.87454589]
 [-0.11470787  1.93870726 -1.94665705  1.51894812]
 [ 0.6882472  -0.28603878  0.32444284  0.55234477]
 [ 1.49120227 -0.95346259  0.32444284  0.23014365]
 [-1.720618   -0.73098799  0.32444284 -1.05866081]]


In [4]:
# MIN-MAX-SCALING
# x-min(set(x))/max(set(x))-min(set(x))

max_arr = numpy.max(table,axis=0)
min_arr = numpy.min(table,axis=0)
print(max_arr)
print(min_arr)

def get_min_max_scaling(a):
    return [(a[x]-min_arr[x])/(max_arr[x]-min_arr[x]) for x in range(len(a))]
mat = numpy.apply_along_axis(get_min_max_scaling,1,table)
scaled_table=numpy.matrix(mat)
print('*'*50)
print('scaled table now all the cloumn are equal level')
print(scaled_table)

[[     6    140     20 850000]]
[[     2     10      5 400000]]
**************************************************
scaled table now all the cloumn are equal level
[[0.25       0.69230769 0.33333333 0.22222222]
 [0.5        0.07692308 1.         0.        ]
 [0.75       0.23076923 0.66666667 0.77777778]
 [0.5        1.         0.         1.        ]
 [0.75       0.23076923 0.66666667 0.66666667]
 [1.         0.         0.66666667 0.55555556]
 [0.         0.07692308 0.66666667 0.11111111]]


---
# Assignment
- Robust scaling
- Max abs scaling
- power transfer
- unit vector