# write a regression based example for KNN

In [1]:
import math

data = [
    {"height": 175, "age": 25, "weight": 70},
    {"height": 162, "age": 30, "weight": 55},
    {"height": 180, "age": 22, "weight": 80},
    {"height": 155, "age": 28, "weight": 63},
    {"height": 168, "age": 35, "weight": 75},
    {"height": 170, "age": 27, "weight": 68},
    {"height": 163, "age": 31, "weight": 58},
    {"height": 176, "age": 26, "weight": 72},
    {"height": 158, "age": 33, "weight": 60},
    {"height": 182, "age": 29, "weight": 85},
    {"height": 169, "age": 24, "weight": 67},
    {"height": 164, "age": 32, "weight": 59},
    {"height": 177, "age": 28, "weight": 74},
    {"height": 160, "age": 30, "weight": 56},
    {"height": 174, "age": 23, "weight": 69},
    {"height": 167, "age": 34, "weight": 71},
    {"height": 181, "age": 27, "weight": 78},
    {"height": 156, "age": 29, "weight": 62},
    {"height": 172, "age": 31, "weight": 76},
    {"height": 165, "age": 26, "weight": 64},
    {"height": 178, "age": 33, "weight": 79},
    {"height": 159, "age": 28, "weight": 61},
    {"height": 183, "age": 25, "weight": 83},
    {"height": 171, "age": 30, "weight": 77},
    {"height": 166, "age": 27, "weight": 66},
    {"height": 179, "age": 32, "weight": 81},
    {"height": 161, "age": 29, "weight": 57},
    {"height": 175, "age": 34, "weight": 73},
    {"height": 162, "age": 28, "weight": 55},
    {"height": 180, "age": 25, "weight": 82},
    {"height": 155, "age": 31, "weight": 63},
    {"height": 168, "age": 28, "weight": 70},
    {"height": 173, "age": 33, "weight": 68},
    {"height": 157, "age": 26, "weight": 59},
    {"height": 176, "age": 29, "weight": 74},
    {"height": 170, "age": 32, "weight": 76},
    {"height": 184, "age": 30, "weight": 84}
]


In [2]:
import numpy as np
import math
data2 = np.array([(x['height'], x['age'], x['weight']) for x in data])
print(data2)

[[175  25  70]
 [162  30  55]
 [180  22  80]
 [155  28  63]
 [168  35  75]
 [170  27  68]
 [163  31  58]
 [176  26  72]
 [158  33  60]
 [182  29  85]
 [169  24  67]
 [164  32  59]
 [177  28  74]
 [160  30  56]
 [174  23  69]
 [167  34  71]
 [181  27  78]
 [156  29  62]
 [172  31  76]
 [165  26  64]
 [178  33  79]
 [159  28  61]
 [183  25  83]
 [171  30  77]
 [166  27  66]
 [179  32  81]
 [161  29  57]
 [175  34  73]
 [162  28  55]
 [180  25  82]
 [155  31  63]
 [168  28  70]
 [173  33  68]
 [157  26  59]
 [176  29  74]
 [170  32  76]
 [184  30  84]]


In [3]:
# calculate kFector
kFector = int(math.sqrt(len(data2)))
if kFector%2==0:
    kFector+=1
print(kFector)

7


In [4]:
# query data
queryX , queryY= (158,33)

In [5]:
# find distance
distanceList = []
for d in data2:
    distanceList.append((abs(d[0]-queryX)+abs(d[1]-queryY),d[2]))
print(distanceList)

[(25, 70), (7, 55), (33, 80), (8, 63), (12, 75), (18, 68), (7, 58), (25, 72), (0, 60), (28, 85), (20, 67), (7, 59), (24, 74), (5, 56), (26, 69), (10, 71), (29, 78), (6, 62), (16, 76), (14, 64), (20, 79), (6, 61), (33, 83), (16, 77), (14, 66), (22, 81), (7, 57), (18, 73), (9, 55), (30, 82), (5, 63), (15, 70), (15, 68), (8, 59), (22, 74), (13, 76), (29, 84)]


In [6]:
distanceList.sort(key= lambda r : r[0])
distanceList = distanceList[:kFector]
print(distanceList)

[(0, 60), (5, 56), (5, 63), (6, 62), (6, 61), (7, 55), (7, 58)]


In [7]:
final_weights_data = [x[1] for x in distanceList]
print(final_weights_data)

[60, 56, 63, 62, 61, 55, 58]


In [8]:
import statistics as st
p_weight = st.mean(final_weights_data)
print(f"the expected weight for height = {queryX}, age= {queryY} , weight= {p_weight} ")

the expected weight for height = 158, age= 33 , weight= 59 


In [9]:
p_weight
# mse
(60-59)**2/len(distanceList)

0.14285714285714285

In [10]:
p_weight = st.median(final_weights_data)
p_weight

60