# Gray Scale 
- When R G B are the same it makes grayscale
a=b=c
- but imread return matrix with BGR(black green red)


In [2]:
# convert to Matrix
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
print(imageData)
print(type(imageData))
print(imageData.shape)
print(imageData[0][0])

[[[17 12 14]
  [16 11 13]
  [16 11 13]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 [[18 13 15]
  [16 11 13]
  [17 12 14]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 [[18 13 15]
  [17 12 14]
  [17 12 14]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 ...

 [[11 11 11]
  [11 11 11]
  [12 12 12]
  ...
  [43 40 32]
  [38 35 27]
  [34 28 23]]

 [[10 10 10]
  [11 11 11]
  [11 11 11]
  ...
  [34 30 25]
  [37 33 28]
  [37 31 26]]

 [[10 10 10]
  [11 11 11]
  [11 11 11]
  ...
  [33 29 24]
  [34 30 25]
  [37 31 26]]]
<class 'numpy.ndarray'>
(5906, 3937, 3)
[17 12 14]


In [3]:
# convert to grayscale
# method 1
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red= int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        avg = (red+green+blue)/3
        imageData[r][c] = (avg,avg,avg)
cv2.imwrite("tmpfile.jpg",imageData)

True

In [4]:
#method 2 gray scale
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        if red > green:
            clr = red
        else:
            clr = green
        if clr < blue:
            clr = blue
        imageData[r][c] = (clr, clr, clr)  # image file data is being manipulated
cv2.imwrite("tmpfile.jpg", imageData)
print("done")


done


In [5]:
# method 3 gray scale
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        if red < green:
            clr = red
        else:
            clr = green
        if clr > blue:
            clr = blue
        imageData[r][c] = (clr, clr, clr)  # image file data is being manipulated
cv2.imwrite("tmpfile.jpg", imageData)
print("done")


done


In [6]:
# method 4 (recommanded)
# Weighted method or luminosity method
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = (int(rgb[2])*0.3)
        green = (int(rgb[1])*0.59)
        blue = (int(rgb[0])*0.11)
        # imageData[r][c] = (red, green, blue)
        total = red + green + blue
        imageData[r][c] = (total, total, total)
cv2.imwrite("tmpfile.jpg", imageData)



True

In [7]:
# make a progress bar
from tqdm.auto import tqdm
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in tqdm(range(imageData.shape[0])):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = (int(rgb[2])*0.3)
        green = (int(rgb[1])*0.59)
        blue = (int(rgb[0])*0.11)
        # imageData[r][c] = (red, green, blue)
        total = red + green + blue
        imageData[r][c] = (total, total, total)
cv2.imwrite("tmpfile.jpg", imageData)

  0%|          | 0/5906 [00:00<?, ?it/s]

---
# brightness

In [ ]:
# decreses the brightness
import cv2

imageData = cv2.imread("Image_processing/images/image_3.jpeg")
brightness = -150
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        red += brightness
        green += brightness
        blue += brightness
        if red > 255: red = 255
        if red < 0: red = 0
        if green > 255: green = 255
        if green < 0: green = 0
        if blue > 255: blue = 255
        if blue < 0: blue = 0
        imageData[r][c] = (red, green, blue)
cv2.imwrite("tmpfile.jpg", imageData)

In [ ]:
# increses the brightness
import cv2

imageData = cv2.imread("Image_processing/images/image_3.jpeg")
brightness = 150
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        red += brightness
        green += brightness
        blue += brightness
        if red > 255: red = 255
        if red < 0: red = 0
        if green > 255: green = 255
        if green < 0: green = 0
        if blue > 255: blue = 255
        if blue < 0: blue = 0
        imageData[r][c] = (red, green, blue)
cv2.imwrite("tmpfile.jpg", imageData)


# Contrast

In [ ]:
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
contrast = 50
f = (259 * (contrast + 255))/(255 * (259-contrast))
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        newRed = (f*(red-128))+128
        newGreen = (f*(green-128))+128
        newBlue = (f*(blue-128))+128
        if newRed>255 : newRed=255
        if newRed<0 : newRed=0
        if newBlue>255 : newBlue=255
        if newBlue<0: newBlue=0
        if newGreen>255 : newGreen=255
        if newGreen<0: newBlue=0
        imageData[r][c] = (newRed, newBlue, newGreen)
cv2.imwrite("tmpFile.jpg",imageData)
print("check the tmpfile.jpg")

In [ ]:
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
contrast = -150
f = (259 * (contrast + 255))/(255 * (259-contrast))
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        newRed = (f*(red-128))+128
        newGreen = (f*(green-128))+128
        newBlue = (f*(blue-128))+128
        if newRed>255 : newRed=255
        if newRed<0 : newRed=0
        if newBlue>255 : newBlue=255
        if newBlue<0: newBlue=0
        if newGreen>255 : newGreen=255
        if newGreen<0: newBlue=0
        imageData[r][c] = (newRed, newBlue, newGreen)
cv2.imwrite("tmpFile.jpg",imageData)
print("check the tmpfile.jpg")

# Crop

In [ ]:

import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_2.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
# print(imageData[0][0])
# newImage = numpy.zeros((cropSize[1], cropSize[0], 3))

r = r1
while r <= r2:
    print(r)
    imageData[r][c1] = (0, 0, 255)  # black bgr code
    imageData[r][c2] = (0, 0, 255)
    r += 1

c=c1
while c <=c2:
    print(c)
    imageData[r1][c] = (0,0,255)
    imageData[r2][c] = (0,0,255)
    c +=1

cv2.imwrite("tmp.jpeg", imageData)
print("Done")

In [ ]:
# import numpy
# a = numpy.zeros((10,3))
# print(a)

import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
newImage = numpy.zeros((cropSize[1], cropSize[0], 3))
rr = 0
r = r1
while r <= r2:
    cc = 0
    c = c1
    while c <= c2:
        newImage[rr][cc] = imageData[r][c]
        cc += 1
        c += 1
    rr += 1
    r += 1
cv2.imwrite("tmp.jpeg", newImage)
print("Done")

In [ ]:
# import numpy
# a = numpy.zeros((10,3))
# print(a)

import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
newImage = numpy.zeros((cropSize[1], cropSize[0], 3))
rr = 0
r = r1
while r <= r2:
    cc = 0
    c = c1
    while c <= c2:
        newImage[rr][cc] = imageData[r][c]
        cc += 1
        c += 1
    rr += 1
    r += 1
cv2.imwrite("tmp.jpeg", newImage)
print("Done")