# Gray Scale 
- When R G B are the same it makes grayscale
a=b=c
- but imread return matrix with BGR(black green red)


In [2]:
# convert to Matrix
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
print(imageData)
print(type(imageData))
print(imageData.shape)
print(imageData[0][0])

[[[17 12 14]
  [16 11 13]
  [16 11 13]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 [[18 13 15]
  [16 11 13]
  [17 12 14]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 [[18 13 15]
  [17 12 14]
  [17 12 14]
  ...
  [13 11 11]
  [13 11 11]
  [11 11 11]]

 ...

 [[11 11 11]
  [11 11 11]
  [12 12 12]
  ...
  [43 40 32]
  [38 35 27]
  [34 28 23]]

 [[10 10 10]
  [11 11 11]
  [11 11 11]
  ...
  [34 30 25]
  [37 33 28]
  [37 31 26]]

 [[10 10 10]
  [11 11 11]
  [11 11 11]
  ...
  [33 29 24]
  [34 30 25]
  [37 31 26]]]
<class 'numpy.ndarray'>
(5906, 3937, 3)
[17 12 14]


In [3]:
# convert to grayscale
# method 1
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red= int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        avg = (red+green+blue)/3
        imageData[r][c] = (avg,avg,avg)
cv2.imwrite("tmpfile.jpg",imageData)

True

In [4]:
#method 2 gray scale
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        if red > green:
            clr = red
        else:
            clr = green
        if clr < blue:
            clr = blue
        imageData[r][c] = (clr, clr, clr)  # image file data is being manipulated
cv2.imwrite("tmpfile.jpg", imageData)
print("done")


done


In [5]:
# method 3 gray scale
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = int(rgb[2])
        green = int(rgb[1])
        blue = int(rgb[0])
        if red < green:
            clr = red
        else:
            clr = green
        if clr > blue:
            clr = blue
        imageData[r][c] = (clr, clr, clr)  # image file data is being manipulated
cv2.imwrite("tmpfile.jpg", imageData)
print("done")


done


In [6]:
# method 4 (recommanded)
# Weighted method or luminosity method
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = (int(rgb[2])*0.3)
        green = (int(rgb[1])*0.59)
        blue = (int(rgb[0])*0.11)
        # imageData[r][c] = (red, green, blue)
        total = red + green + blue
        imageData[r][c] = (total, total, total)
cv2.imwrite("tmpfile.jpg", imageData)



True

In [7]:
# make a progress bar
from tqdm.auto import tqdm
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
for r in tqdm(range(imageData.shape[0])):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = (int(rgb[2])*0.3)
        green = (int(rgb[1])*0.59)
        blue = (int(rgb[0])*0.11)
        # imageData[r][c] = (red, green, blue)
        total = red + green + blue
        imageData[r][c] = (total, total, total)
cv2.imwrite("tmpfile.jpg", imageData)

  0%|          | 0/5906 [00:00<?, ?it/s]

True

---
# brightness

In [8]:
# decreses the brightness
import cv2

imageData = cv2.imread("Image_processing/images/image_3.jpeg")
brightness = -150
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        red += brightness
        green += brightness
        blue += brightness
        if red > 255: red = 255
        if red < 0: red = 0
        if green > 255: green = 255
        if green < 0: green = 0
        if blue > 255: blue = 255
        if blue < 0: blue = 0
        imageData[r][c] = (red, green, blue)
cv2.imwrite("tmpfile.jpg", imageData)

True

In [9]:
# increses the brightness
import cv2

imageData = cv2.imread("Image_processing/images/image_3.jpeg")
brightness = 150
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        red += brightness
        green += brightness
        blue += brightness
        if red > 255: red = 255
        if red < 0: red = 0
        if green > 255: green = 255
        if green < 0: green = 0
        if blue > 255: blue = 255
        if blue < 0: blue = 0
        imageData[r][c] = (red, green, blue)
cv2.imwrite("tmpfile.jpg", imageData)


True

# Contrast

In [10]:
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
contrast = 50
f = (259 * (contrast + 255))/(255 * (259-contrast))
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        newRed = (f*(red-128))+128
        newGreen = (f*(green-128))+128
        newBlue = (f*(blue-128))+128
        if newRed>255 : newRed=255
        if newRed<0 : newRed=0
        if newBlue>255 : newBlue=255
        if newBlue<0: newBlue=0
        if newGreen>255 : newGreen=255
        if newGreen<0: newBlue=0
        imageData[r][c] = (newRed, newBlue, newGreen)
cv2.imwrite("tmpFile.jpg",imageData)
print("check the tmpfile.jpg")

check the tmpfile.jpg


In [11]:
import cv2
imageData = cv2.imread("Image_processing/images/image_2.jpeg")
contrast = -150
f = (259 * (contrast + 255))/(255 * (259-contrast))
for r in range(imageData.shape[0]):
    for c in range(imageData.shape[1]):
        rgb = imageData[r][c]
        red = rgb[2]
        green = rgb[1]
        blue = rgb[0]
        newRed = (f*(red-128))+128
        newGreen = (f*(green-128))+128
        newBlue = (f*(blue-128))+128
        if newRed>255 : newRed=255
        if newRed<0 : newRed=0
        if newBlue>255 : newBlue=255
        if newBlue<0: newBlue=0
        if newGreen>255 : newGreen=255
        if newGreen<0: newBlue=0
        imageData[r][c] = (newRed, newBlue, newGreen)
cv2.imwrite("tmpFile.jpg",imageData)
print("check the tmpfile.jpg")

check the tmpfile.jpg


# Crop

In [12]:

import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_2.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
# print(imageData[0][0])
# newImage = numpy.zeros((cropSize[1], cropSize[0], 3))

r = r1
while r <= r2:
    print(r)
    imageData[r][c1] = (0, 0, 255)  # black bgr code
    imageData[r][c2] = (0, 0, 255)
    r += 1

c=c1
while c <=c2:
    print(c)
    imageData[r1][c] = (0,0,255)
    imageData[r2][c] = (0,0,255)
    c +=1

cv2.imwrite("tmp.jpeg", imageData)
print("Done")

Actual Sie :  (5906, 3937, 3)
(300, 100)
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239

In [13]:
# import numpy
# a = numpy.zeros((10,3))
# print(a)

import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
newImage = numpy.zeros((cropSize[1], cropSize[0], 3))
rr = 0
r = r1
while r <= r2:
    cc = 0
    c = c1
    while c <= c2:
        newImage[rr][cc] = imageData[r][c]
        cc += 1
        c += 1
    rr += 1
    r += 1
cv2.imwrite("tmp.jpeg", newImage)
print("Done")

Actual Sie :  (3024, 4032, 3)
(300, 100)
Done


In [14]:


import numpy
import cv2

imageData = cv2.imread("Image_processing/images/image_1.jpeg")
cropFrom = (100, 200)
cropSize = (400, 300)

c1 = cropFrom[0]
r1 = cropFrom[1]
c2 = cropSize[0] - 1
r2 = cropSize[1] - 1

if r2 >= imageData.shape[0]:
    r2 = imageData.shape[0] - 1
if c2 >= imageData.shape[1]:
    c2 = imageData.shape[1] - 1

print("Actual Sie : ", imageData.shape)
cropSize = (c2 - c1 + 1, r2 - r1 + 1)
print(cropSize)
newImage = numpy.zeros((cropSize[1], cropSize[0], 3))
rr = 0
r = r1
while r <= r2:
    cc = 0
    c = c1
    while c <= c2:
        newImage[rr][cc] = imageData[r][c]
        cc += 1
        c += 1
    rr += 1
    r += 1
cv2.imwrite("tmp.jpeg", newImage)
print("Done")

Actual Sie :  (3024, 4032, 3)
(300, 100)
Done
