In [51]:
#SPlit the matrix 
import numpy

In [41]:
#HOrizantaly
a = numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
print("Horizantally Split")
b = numpy.hsplit(a,2)
print('a\n',a)
print('b\n',b)
c=b[0]
d=b[1]
print('c\n',c)
print('d\n',d)

#Verticaly
print("vertically Split")
e=numpy.vsplit(c,2)
f=numpy.vsplit(d,2)
g=e[0]
h=e[1]
i=f[0]
j=f[1]
print('g\n',g)
print('h\n',h)
print('i\n',i)
print('j\n',j)




Horizantally Split
a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [matrix([[ 10,  20],
        [ 50,  60],
        [ 90, 100],
        [130, 140]]), matrix([[ 30,  40],
        [ 70,  80],
        [110, 120],
        [150, 160]])]
c
 [[ 10  20]
 [ 50  60]
 [ 90 100]
 [130 140]]
d
 [[ 30  40]
 [ 70  80]
 [110 120]
 [150 160]]
vertically Split
g
 [[10 20]
 [50 60]]
h
 [[ 90 100]
 [130 140]]
i
 [[30 40]
 [70 80]]
j
 [[110 120]
 [150 160]]


# Sparse Matrix

In [42]:
import sys
!{sys.executable} -m pip install scipy

You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 -m pip install --upgrade pip' command.


In [43]:
import scipy.sparse
a=numpy.matrix(((24,0,0,1),(0,1,20,0),(0,0,0,1),(1,4,0,2),(0,0,0,1)))
print('a\n',a)

#CSR -> Compressed sparse column
ca = scipy.sparse.csr_matrix(a)
print('compressed form\n',ca)


a
 [[24  0  0  1]
 [ 0  1 20  0]
 [ 0  0  0  1]
 [ 1  4  0  2]
 [ 0  0  0  1]]
compressed form
   (0, 0)	24
  (0, 3)	1
  (1, 1)	1
  (1, 2)	20
  (2, 3)	1
  (3, 0)	1
  (3, 1)	4
  (3, 3)	2
  (4, 3)	1


# some time it can be a wrong becouse of extra space consume like 
#Example

In [44]:
a= numpy.matrix(((24,20,10,1),(0,1,20,50),(60,40,0,1),(1,4,0,2),(24,21,0,1),(0,54,0,1)))
print('a\n',a)

#CSR -> Compressed sparse column
ca = scipy.sparse.csr_matrix(a)
print('compressed form\n',ca)
print("="*30)
print("Check the matrix is sparse-able")
#error hai direct passed matix a
print(scipy.sparse.issparse(a)) #--> Error solution in next block



a
 [[24 20 10  1]
 [ 0  1 20 50]
 [60 40  0  1]
 [ 1  4  0  2]
 [24 21  0  1]
 [ 0 54  0  1]]
compressed form
   (0, 0)	24
  (0, 1)	20
  (0, 2)	10
  (0, 3)	1
  (1, 1)	1
  (1, 2)	20
  (1, 3)	50
  (2, 0)	60
  (2, 1)	40
  (2, 3)	1
  (3, 0)	1
  (3, 1)	4
  (3, 3)	2
  (4, 0)	24
  (4, 1)	21
  (4, 3)	1
  (5, 1)	54
  (5, 3)	1
Check the matrix is sparse-able
False


In [45]:
# error kya hai jo issparce hai wo csr_matrix type ka object except karega par humne usme direct numpy.matrix ka 
# object pass kar diya or is condition me wo always false hi deta hai


# Let see the Example :
#      problem 
    
a = numpy.matrix(((0,0,0),(0,0,0),(1,0,0)))
print(a)
print(scipy.sparse.issparse(a)) # --> always false


# sol:
b = scipy.sparse.csr_matrix(a)
print(scipy.sparse.issparse(b))
print("isSparse method needs a csr_matrix not normal matrix")



[[0 0 0]
 [0 0 0]
 [1 0 0]]
False
True
isSparse method needs a csr_matrix not normal matrix


# implementation of isSparse and other methods

In [46]:
a= numpy.matrix(((24,20,10,1),(0,1,20,50),(60,40,0,1),(1,4,0,2),(24,21,0,1),(0,54,0,1)))
print('a\n',a)
k=numpy.count_nonzero(a)
print('non zero count',k)
print('shape',a.shape)
rows = a.shape[0]
columns=a.shape[1]
print('row : ',rows)
print('column : ',columns)
sz = a.size
print('size : ',sz)
x = 1-(k/sz)
if x > 0.5 : print("True")
else : print("False")
    







a
 [[24 20 10  1]
 [ 0  1 20 50]
 [60 40  0  1]
 [ 1  4  0  2]
 [24 21  0  1]
 [ 0 54  0  1]]
non zero count 18
shape (6, 4)
row :  6
column :  4
size :  24
False


# Rank and Trace

In [47]:
a = numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120)))
b=numpy.linalg.matrix_rank(a)
print('a\n',a)
print('Rank : ',b)

a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Rank :  2


In [48]:
c = numpy.linalg.matrix_rank(a)
print('a\n',a)
print('Trace : ',c)


a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Trace :  2


# Squre and Power ^3 Matrix

In [49]:


a = numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
b=numpy.linalg.matrix_power(a,2)
print('a\n',a)
print('a^2 :',b)

c = a*a
print('a*a\n',c)

print('-'*100)

b = numpy.linalg.matrix_power(a,3)
print('a\n',a)
print('a^3',b)
c = a*a*a
print('a*a*a\n',c)



a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
a^2 : [[ 9000 10000 11000 12000]
 [20200 22800 25400 28000]
 [31400 35600 39800 44000]
 [42600 48400 54200 60000]]
a*a
 [[ 9000 10000 11000 12000]
 [20200 22800 25400 28000]
 [31400 35600 39800 44000]
 [42600 48400 54200 60000]]
----------------------------------------------------------------------------------------------------
a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
a^3 [[ 3140000  3560000  3980000  4400000]
 [ 7268000  8232000  9196000 10160000]
 [11396000 12904000 14412000 15920000]
 [15524000 17576000 19628000 21680000]]
a*a*a
 [[ 3140000  3560000  3980000  4400000]
 [ 7268000  8232000  9196000 10160000]
 [11396000 12904000 14412000 15920000]
 [15524000 17576000 19628000 21680000]]


# Eigen values , Eigen Vectors

In [50]:
a = numpy.matrix(((1,2,30,40),(20,3,40,-2),(-3,40,3,20),(50,0,4,2)))
print('a\n',a)
b,c = numpy.linalg.eig(a)
print('eigen values \n ',b)
print('eigen vectors \n',c)



a
 [[ 1  2 30 40]
 [20  3 40 -2]
 [-3 40  3 20]
 [50  0  4  2]]
eigen values 
  [-40.24330491+17.24081033j -40.24330491-17.24081033j
  62.5550599  +0.j          26.93154992 +0.j        ]
eigen vectors 
 [[ 0.03043304+0.42208635j  0.03043304-0.42208635j  0.56032891+0.j
   0.33588464+0.j        ]
 [ 0.52704032-0.00459822j  0.52704032+0.00459822j  0.48073115+0.j
  -0.55521945+0.j        ]
 [-0.57348595+0.j         -0.57348595-0.j          0.46023795+0.j
  -0.47021524+0.j        ]
 [ 0.19045569-0.42185873j  0.19045569+0.42185873j  0.49306197+0.j
   0.59817263+0.j        ]]
