# Matrix operations

In [3]:
import numpy
a = numpy.matrix(((10 , 20 ,30),(4,3,4)))
b = numpy.matrix(((1,2),(3,4),(5,6)))
print('a\n' ,a)
print('b\n' ,b)
c=a*b
print('a*b\n' ,c)


a
 [[10 20 30]
 [ 4  3  4]]
b
 [[1 2]
 [3 4]
 [5 6]]
a*b
 [[220 280]
 [ 33  44]]


- m1 row(2)*clumn(3)
- m2   row(3)*column(2)
 ==> result matrix is 2 * 2 
` the matix is valdate in m1_clumn(3)==m2_row(3)`

In [4]:
# ex 2 : 
a = numpy.matrix(((10,20,30),(4,3,4)))
b= numpy.matrix(((1,2,3,5),(4,3,4,3),(5,6,3,4)))
print('a\n' , a)
print('b\n' ,b)
c = a*b
print('a*b\n' ,c)



a
 [[10 20 30]
 [ 4  3  4]]
b
 [[1 2 3 5]
 [4 3 4 3]
 [5 6 3 4]]
a*b
 [[240 260 200 230]
 [ 36  41  36  45]]


In [5]:
# ex 3 : 
a = numpy.matrix(((10,20,30),(4,3,4)))
b= numpy.matrix(((1,2,3,5),(4,3,4,3)))
print('a\n' , a)
print('b\n' ,b)
c = a*b
print('a*b\n' ,c)


a
 [[10 20 30]
 [ 4  3  4]]
b
 [[1 2 3 5]
 [4 3 4 3]]


ValueError: shapes (2,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

# realtime Example


|class| Sports | Computer | Music |
|-----|--------|----------|-------|
| IX  |    5    |    10    |   15  |
| X   |    6    |    15    |   2   |
| XI  |    4    |    15    |   10  |
| XII |    24   |    16    |   8   |

> How much maney will be collected every month
- Fee 
- sports 100
- computer 200
- music 150


In [6]:
# 4X3 | 3X1 ==> Result  4X1
import numpy

In [7]:
a = numpy.matrix(((5,10,15),(6,15,2),(4,15,10),(24,16,8)))
b = numpy.matrix(((100),(200),(300))) # ---> it wants tuple
print('a\n' , a)
print('b\n' ,b)
c = a*b
print('a*b\n' ,c)
# see the below the right code

a
 [[ 5 10 15]
 [ 6 15  2]
 [ 4 15 10]
 [24 16  8]]
b
 [[100 200 300]]


ValueError: shapes (4,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [8]:
# let's see the Example
a = (10,20,30)
print(a,type(a))
b = (100) #int
print(b, type(b))
c = (200 ,) #tuple
print(c , type(c))

(10, 20, 30) <class 'tuple'>
100 <class 'int'>
(200,) <class 'tuple'>


In [9]:
a = numpy.matrix(((5,10,15),(6,15,2),(4,15,10),(24,16,8)))
b = numpy.matrix(((100,),(200,),(300,))) 
print('a\n' , a)
print('b\n' ,b)
c = a*b
print('a*b\n' ,c)
# find the sum 
t = numpy.sum(c)
print(f"Total fee to be collected every month {t}")


a
 [[ 5 10 15]
 [ 6 15  2]
 [ 4 15 10]
 [24 16  8]]
b
 [[100]
 [200]
 [300]]
a*b
 [[7000]
 [4200]
 [6400]
 [8000]]
Total fee to be collected every month 25600


In [10]:
# find the sum 
t = numpy.sum(c)
print(f"Total fee to be collected every month {t}")


Total fee to be collected every month 25600


# matix operations with Scaler value

In [11]:
import numpy

In [12]:
#add

a = numpy.matrix(((10 , 20) , (30,40)))
b = a+10
print('a\n' ,a)
print('a+10' , b)
b = numpy.add(a , 10)
print('a+10\n' ,b)

a
 [[10 20]
 [30 40]]
a+10 [[20 30]
 [40 50]]
a+10
 [[20 30]
 [40 50]]


In [13]:
#subtract

a = numpy.matrix(((10 , 20) , (30,40)))
b = a-10
print('a\n' ,a)
print('a-10' , b)
b = numpy.subtract(a , 10)
print('a-10\n' ,b)

a
 [[10 20]
 [30 40]]
a-10 [[ 0 10]
 [20 30]]
a-10
 [[ 0 10]
 [20 30]]


In [14]:
# multiply

a = numpy.matrix(((10 , 20) , (30,40)))
b = a*10
print('a\n' ,a)
print('a*10' , b)
b = numpy.dot(a , 10)
print('a*10\n' ,b)

a
 [[10 20]
 [30 40]]
a*10 [[100 200]
 [300 400]]
a*10
 [[100 200]
 [300 400]]


In [15]:
#divide
a = numpy.matrix(((10 , 20) , (30,40)))
b = a//10
print('a\n' ,a)
print('a divide by 10\n' , b)
b = numpy.divide(a , 10)
print('a/10\n' ,b)

a
 [[10 20]
 [30 40]]
a divide by 10
 [[1 2]
 [3 4]]
a/10
 [[1. 2.]
 [3. 4.]]


In [16]:
# mod 
a = numpy.matrix(((10 , 20) , (30,40)))
b = a%3
print('a\n' ,a)
print('a%10\n' , b)
b = numpy.mod(a , 3)
print('a%10\n' ,b)

a
 [[10 20]
 [30 40]]
a%10
 [[1 2]
 [0 1]]
a%10
 [[1 2]
 [0 1]]


In [17]:
# squrie
a = numpy.matrix(((10 , 20) , (30,40)))
b = a*a
print('a\n' ,a)
print('a^2' , b)
# but there is problem (is not a squire it's a*a)
b =numpy.dot(a,a)
print('a^2\n' ,b)


a
 [[10 20]
 [30 40]]
a^2 [[ 700 1000]
 [1500 2200]]
a^2
 [[ 700 1000]
 [1500 2200]]


# How to Calulate Square 
## Square

In [18]:
import numpy
a = numpy.matrix(((10,20),(30,40)))
b = numpy.square(a)
print('a^2\n' ,b)
b = numpy.power(a,2)
print('a^2\n' , b)
c = numpy.power(a,3)
print('a^3' , c)

a^2
 [[ 100  400]
 [ 900 1600]]
a^2
 [[ 100  400]
 [ 900 1600]]
a^3 [[ 1000  8000]
 [27000 64000]]
