# convert comprass matrix it's orignal Matrix

In [1]:
import numpy
import scipy.sparse
a = numpy.matrix(((0,0,0,1),(1,0,1,0),(0,0,0,0),(0,0,0,1),(0,1,0,0)))
print(type(a))
print('a\n',a)
sc = scipy.sparse.csr_matrix(a)
print('a in compressed from \n',sc)
print(type(sc))
b = sc.toarray()
print('b\n',b)
print(type(b))

# it provide a ndarrya \n now we convert into matrix

c = numpy.matrix(b)
print('c\n',c)
print(type(c))


<class 'numpy.matrix'>
a
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
a in compressed from 
   (0, 3)	1
  (1, 0)	1
  (1, 2)	1
  (3, 3)	1
  (4, 1)	1
<class 'scipy.sparse.csr.csr_matrix'>
b
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.ndarray'>
c
 [[0 0 0 1]
 [1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 1 0 0]]
<class 'numpy.matrix'>


# Ek row me karte hai matrix ko 
#(Flatten karte hai)

In [2]:
import numpy
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*59)
b=a.flatten('C')
print('b\n',b)



a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
-----------------------------------------------------------
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]


In [3]:
a=numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(130,140,150,160)))
print("Row flatten")
b=a.flatten()
print('a\n',a)
print('b\n',b)
print("-"*59)

print("column flatten")
b=a.flatten('F')
print('b\n',b)






Row flatten
a
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
b
 [[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160]]
-----------------------------------------------------------
column flatten
b
 [[ 10  50  90 130  20  60 100 140  30  70 110 150  40  80 120 160]]


In [4]:
a=numpy.matrix(((1,2,3,4,41),(5,6,7,8,81),(9,10,11,12,91)))
b=a.flatten()
print('a\n',a)
print('b\n',b)
c=b.reshape(5,3)
print('c\n',c)

d=b.reshape(3,5)
print('d\n',d)


a
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]
b
 [[ 1  2  3  4 41  5  6  7  8 81  9 10 11 12 91]]
c
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]
d
 [[ 1  2  3  4 41]
 [ 5  6  7  8 81]
 [ 9 10 11 12 91]]


In [5]:
#you can reshape matrix directly
e=a.reshape(5,3)
print('e\n',e)

e
 [[ 1  2  3]
 [ 4 41  5]
 [ 6  7  8]
 [81  9 10]
 [11 12 91]]


In [6]:
# can not be left any element
f=a.reshape(2,4) # Wrong
# and not add any element using reshape
f=a.reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (2,4)

# Importent Point releated to reference

In [7]:
import numpy
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[1010   20   30   40]
 [  50   60   70   80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]


In [8]:
# if you need to make a copy

a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.copy()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)



a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]


In [9]:
# another operation is view()
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
print('a\n',a)
b=a.view()
print('b\n',b)
print('-'*40)
b[0,0]=1010
print('a\n',a)
print('b\n',b)


print(id(a),id(b))

print("diff is A obj , B obj  -> is point to main obj ")

print("prof of concept :")
a =numpy.matrix(((10,20,30,40),(50,60,70,80)))
b=a
c=a.copy()
d=a.view()

print('id of a\n',id(a))
print('id of b\n',id(b))
print('id of c\n',id(c))
print('id of d\n',id(d))

print('a,b address is same \nbut c,d address are not same')


a
 [[10 20 30 40]
 [50 60 70 80]]
b
 [[10 20 30 40]
 [50 60 70 80]]
----------------------------------------
a
 [[1010   20   30   40]
 [  50   60   70   80]]
b
 [[1010   20   30   40]
 [  50   60   70   80]]
140379155953696 140379155411904
diff is A obj , B obj  -> is point to main obj 
prof of concept :
id of a
 140379155953920
id of b
 140379155953920
id of c
 140379155411904
id of d
 140379155412800
a,b address is same 
but c,d address are not same


In [10]:
# crate a element with a range
a=numpy.arange(100)
print('a\n',a)
b=a.reshape(5,20)
print('b\n',b)
#-------------------
print("-"*40)
c=numpy.arange(50).reshape(2,25)
print('c\n',c)


a
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
b
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
----------------------------------------
c
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [11]:
a=numpy.random.randint(100,size=50)
print('a\n',a)
print(type(a))
b = numpy.random.randint(100,size=(5,4))
print('b\n',b)
print(type(b))

c=numpy.matrix(b)
print('c\n',c)
print(type(c))


a
 [71 81 50 35 62 90 61 67 29 99 17 61 49 15 38 36 16 73 66 74 20 61 31 96
 39 22 47 10 95 58 60 36  1 27 25  9 98 23 89 23 12  1 43 27 77 29 50 88
 77 57]
<class 'numpy.ndarray'>
b
 [[40  0 41 88]
 [53 54 75 71]
 [75 21 75 60]
 [62 69 50 35]
 [62 73 60 74]]
<class 'numpy.ndarray'>
c
 [[40  0 41 88]
 [53 54 75 71]
 [75 21 75 60]
 [62 69 50 35]
 [62 73 60 74]]
<class 'numpy.matrix'>


In [12]:
a = numpy.random.choice([10,2,3,-1,540,40,30],size=(5,8))
print('a\n',a)

a
 [[ 30  -1   2  30   3   2  -1 540]
 [  3 540  -1  40   3  40 540  -1]
 [  3 540  -1   2   2  30  -1  30]
 [ 40  -1  10  10   2  10  40   2]
 [ 40  40  10 540  -1  -1  30   2]]


In [13]:
# When pass a functions
def get_max(a):
    max=a[0]
    for x in range(1,len(a)):
        if a[x]>max: max=a[x]
    return max

a =numpy.random.randint(100,size=(5,4))
print('a\n',a)
print(type(a))

c =numpy.apply_along_axis(get_max,1,a)
print('c\n',c)
print(type(c))

c= numpy.apply_along_axis(get_max,0,a)
print('c\n',c)





a
 [[10 65  6  4]
 [ 7 73 47 67]
 [83 34 97 47]
 [54 69 78 72]
 [82 52 37 76]]
<class 'numpy.ndarray'>
c
 [65 73 97 78 82]
<class 'numpy.ndarray'>
c
 [83 73 97 76]
